Documenta el caso de uso de la predicción de temperaturas por municipio y añade fuzzy search
pablo-moreno/python-aemet pull request #28
Opened 2021-04-03 18:40 UTC by jmrr

## Resumen

- [x] Añade fuzzy search a la búsqueda por municipio devolviendo el municipio más cercano a la secuencia de entrada.
- [x] Documenta este caso de uso en el directorio `docs`, potencialmente se puede mover a la wiki
 
### Descripción de la contribución

La motivación fue que al usar la interfaz CLI me di cuenta de que el método `buscar` de la clase `Municipio` devolvia una lista con los municipios cuya busqueda simple por nombre arrojara los resultados que contuvieran la cadena de entrada.

Pienso que quiza devolver el municipio mas cercano de una busqueda hecha con `fuzzywuzzy` y la distancia Levenshtein que es lo que quiza el usuario anda buscando.

Por ejemplo, una cadena incompleta como:

```
 aemet -p "Rivas" -f /home/jose/Dropbox/keys/aemet.key
```
Arrojaria:

Predicción de temperaturas para Rivas-Vaciamadrid:

2021-04-03T00:00:00
Máxima: 21
Mínima: 6
...
```

Y otra con faltas de ortografia como:
```
aemet -p "Velez Malaga" -f /home/jose/Dropbox/keys/aemet.key
```
Resultaria:

```
Predicción de temperaturas para Vélez-Málaga:

2021-04-03T00:00:00
Máxima: 25
Mínima: 13
...
```

Como lo veis?

2021-04-03 23:23 UTC, pablo-moreno requested changes

2021-04-03 23:23 UTC, pablo-moreno commented on aemet/models.py
> +            nombres_municipios = list(map(lambda m: m.get("NOMBRE"), Municipio.MUNICIPIOS))
Entiendo la funcionalidad y me parece bien mejorar la búsqueda de municipios en general, pero quiero evitar añadir más dependencias de las necesarias y creo que no es el objetivo principal de lo que nos ocupa.

2021-04-03 23:23 UTC, pablo-moreno commented on docs/README.md
> +  Clona el repo `git clone git@github.com:pablo-moreno/python-aemet.git && cd python-aemet`
Aquí sería mejor hablar de instalar la librería desde pypi, que es como está en el README.md

```sh
pip install python-aemet
```

2021-04-03 23:29 UTC, jmrr commented on aemet/models.py
> +            nombres_municipios = list(map(lambda m: m.get("NOMBRE"), Municipio.MUNICIPIOS))
Sí tienes razón. Te parece que cree un issue para mejorar la búsqueda? Es que tal cual estaba en el init no funcionaba, devuelve una lista de todos los municipios con la palabra que metes en el argumento en la línea de comandos.

2021-04-03 23:30 UTC, jmrr commented on docs/README.md
> +  Clona el repo `git clone git@github.com:pablo-moreno/python-aemet.git && cd python-aemet`
Cierto, ida de olla. Entonces quito todo lo del virtualenv que eso es gestión de entorno. Que cada usuario se apañe digamos.

2021-04-04 19:56 UTC, jmrr commented
Cierro esta porque he abierto otra PR con solo la documentacion #30 y otra con el fuzzysearch #31.

2021-04-04 19:56 UTC, closed without merging